#pragma once

#include "CoreMinimal.h"

/**
 * Centralized error codes for consistent error handling
 * Organized by domain and operation type
 */
namespace VibeUE
{
namespace ErrorCodes
{
	// Parameter validation errors (1000-1099)
	constexpr const TCHAR* PARAM_MISSING = TEXT("PARAM_MISSING");
	constexpr const TCHAR* PARAM_INVALID = TEXT("PARAM_INVALID");
	constexpr const TCHAR* PARAM_TYPE_MISMATCH = TEXT("PARAM_TYPE_MISMATCH");

	// Blueprint errors (2000-2099)
	constexpr const TCHAR* BLUEPRINT_NOT_FOUND = TEXT("BLUEPRINT_NOT_FOUND");
	constexpr const TCHAR* BLUEPRINT_LOAD_FAILED = TEXT("BLUEPRINT_LOAD_FAILED");
	constexpr const TCHAR* BLUEPRINT_COMPILATION_FAILED = TEXT("BLUEPRINT_COMPILATION_FAILED");
	constexpr const TCHAR* BLUEPRINT_ALREADY_EXISTS = TEXT("BLUEPRINT_ALREADY_EXISTS");
	constexpr const TCHAR* BLUEPRINT_INVALID_PARENT = TEXT("BLUEPRINT_INVALID_PARENT");

	// Variable errors (2100-2199)
	constexpr const TCHAR* VARIABLE_NOT_FOUND = TEXT("VARIABLE_NOT_FOUND");
	constexpr const TCHAR* VARIABLE_ALREADY_EXISTS = TEXT("VARIABLE_ALREADY_EXISTS");
	constexpr const TCHAR* VARIABLE_TYPE_INVALID = TEXT("VARIABLE_TYPE_INVALID");
	constexpr const TCHAR* VARIABLE_CREATE_FAILED = TEXT("VARIABLE_CREATE_FAILED");
	constexpr const TCHAR* VARIABLE_DELETE_FAILED = TEXT("VARIABLE_DELETE_FAILED");
	constexpr const TCHAR* VARIABLE_UPDATE_FAILED = TEXT("VARIABLE_UPDATE_FAILED");

	// Component errors (2200-2299)
	constexpr const TCHAR* COMPONENT_NOT_FOUND = TEXT("COMPONENT_NOT_FOUND");
	constexpr const TCHAR* COMPONENT_TYPE_INVALID = TEXT("COMPONENT_TYPE_INVALID");
	constexpr const TCHAR* COMPONENT_ADD_FAILED = TEXT("COMPONENT_ADD_FAILED");

	// Property errors (2300-2399)
	constexpr const TCHAR* PROPERTY_NOT_FOUND = TEXT("PROPERTY_NOT_FOUND");
	constexpr const TCHAR* PROPERTY_READ_ONLY = TEXT("PROPERTY_READ_ONLY");
	constexpr const TCHAR* PROPERTY_TYPE_MISMATCH = TEXT("PROPERTY_TYPE_MISMATCH");
	constexpr const TCHAR* PROPERTY_SET_FAILED = TEXT("PROPERTY_SET_FAILED");
	constexpr const TCHAR* PROPERTY_GET_FAILED = TEXT("PROPERTY_GET_FAILED");

	// Node errors (2400-2499)
	constexpr const TCHAR* NODE_NOT_FOUND = TEXT("NODE_NOT_FOUND");
	constexpr const TCHAR* NODE_CREATE_FAILED = TEXT("NODE_CREATE_FAILED");
	constexpr const TCHAR* NODE_TYPE_INVALID = TEXT("NODE_TYPE_INVALID");
	constexpr const TCHAR* PIN_NOT_FOUND = TEXT("PIN_NOT_FOUND");
	constexpr const TCHAR* PIN_CONNECTION_FAILED = TEXT("PIN_CONNECTION_FAILED");
	constexpr const TCHAR* PIN_TYPE_INCOMPATIBLE = TEXT("PIN_TYPE_INCOMPATIBLE");

	// UMG/Widget errors (3000-3099)
	constexpr const TCHAR* WIDGET_NOT_FOUND = TEXT("WIDGET_NOT_FOUND");
	constexpr const TCHAR* WIDGET_CREATE_FAILED = TEXT("WIDGET_CREATE_FAILED");
	constexpr const TCHAR* WIDGET_TYPE_INVALID = TEXT("WIDGET_TYPE_INVALID");
	constexpr const TCHAR* WIDGET_COMPONENT_NOT_FOUND = TEXT("WIDGET_COMPONENT_NOT_FOUND");
	constexpr const TCHAR* WIDGET_PARENT_INCOMPATIBLE = TEXT("WIDGET_PARENT_INCOMPATIBLE");

	// Asset errors (4000-4099)
	constexpr const TCHAR* ASSET_NOT_FOUND = TEXT("ASSET_NOT_FOUND");
	constexpr const TCHAR* ASSET_IMPORT_FAILED = TEXT("ASSET_IMPORT_FAILED");
	constexpr const TCHAR* ASSET_EXPORT_FAILED = TEXT("ASSET_EXPORT_FAILED");

	// Type resolution errors (5000-5099)
	constexpr const TCHAR* TYPE_NOT_FOUND = TEXT("TYPE_NOT_FOUND");
	constexpr const TCHAR* TYPE_RESOLVE_FAILED = TEXT("TYPE_RESOLVE_FAILED");
	constexpr const TCHAR* TYPE_INVALID = TEXT("TYPE_INVALID");

	// System errors (9000-9099)
	constexpr const TCHAR* OPERATION_NOT_SUPPORTED = TEXT("OPERATION_NOT_SUPPORTED");
	constexpr const TCHAR* INTERNAL_ERROR = TEXT("INTERNAL_ERROR");
	constexpr const TCHAR* TIMEOUT = TEXT("TIMEOUT");
}
}
